apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: the-project-staging

resources:
- ./../../base
- application.yaml

patches:
- path: todo-config.yaml

images:
- name: PROJECT/todo-app
  newName: europe-north1-docker.pkg.dev/dwk-gke-478610/dwk-docker-repository/todo-app
  newTag: staging-c39b4a0c24baaff1b17cb1412f0fdf4f5d3d5734
- name: PROJECT/todo-app-writer
  newName: europe-north1-docker.pkg.dev/dwk-gke-478610/dwk-docker-repository/todo-app-writer
  newTag: staging-c39b4a0c24baaff1b17cb1412f0fdf4f5d3d5734
- name: PROJECT/todo-backend
  newName: europe-north1-docker.pkg.dev/dwk-gke-478610/dwk-docker-repository/todo-backend
  newTag: staging-c39b4a0c24baaff1b17cb1412f0fdf4f5d3d5734
- name: PROJECT/todo-broadcaster
  newName: europe-north1-docker.pkg.dev/dwk-gke-478610/dwk-docker-repository/todo-broadcaster
  newTag: staging-c39b4a0c24baaff1b17cb1412f0fdf4f5d3d5734
- name: PROJECT/todo-cronjob
  newName: europe-north1-docker.pkg.dev/dwk-gke-478610/dwk-docker-repository/todo-cronjob
  newTag: staging-c39b4a0c24baaff1b17cb1412f0fdf4f5d3d5734
