apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: the-project-prod
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/sunkken/dwk-project-gitops-repo
      path: "overlays/prod"
      targetRevision: ">=4.8"
      ref: git-prod

    - repoURL: https://charts.bitnami.com/bitnami
      chart: nats
      targetRevision: "9.0.28"
      helm:
        valueFiles:
          - $git-prod/base/nats-values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: the-project-prod

  syncPolicy:
    automated:
      prune: true
      selfHeal: true