apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: project

resources:
- todo-gateway.yaml
- todo-config.yaml
- tododb.yaml
- todo-backend.yaml
- todo-app.yaml
- todo-broadcaster.yaml
- todo-cronjob.yaml
- nats-svc.yaml