auth:
  enabled: false

image:
  registry: docker.io
  repository: bitnamilegacy/nats
  tag: 2.11.8-debian-12-r0
  pullPolicy: IfNotPresent

metrics:
  enabled: true
  image:
    registry: docker.io
    repository: bitnamilegacy/nats-exporter
    tag: 0.15.0-debian-12-r0
    pullPolicy: IfNotPresent
  serviceMonitor:
    enabled: true
    namespace: prometheus

persistence:
  enabled: false
